# Generated by Django 5.2.13 on 2026-04-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.election'),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
    ]
